site_name: My Docs
site_url: https://example.com/
nav:
    - Home: index.md
    - About: about.md
    - Test Pages:
        - Overview: test-pages/index.md
        - Test: test-pages/test.md
        - Test 2: test-pages/test2.md
# theme: readthedocs
